# Configuração do Banco de Dados
database:
  path: "analysis.db"
  backup_retention_days: 7
  cache_enabled: true
  cache_ttl_days: 1

# Configuração da API
api:
  key: "CLAUDE_KEY_HERE"
  model: "claude-3-haiku-20240307"
  max_tokens: 4000
  temperature: 0
  timeout: 30
  max_retries: 3

# Configuração de Análise
analysis:
  min_severity: 1
  auto_fix_enabled: false
  auto_fix_min_severity: 4
  monitor_interval: 300
  ignore_patterns:
    - "*.bak"
    - "*.~pas"
    - "*.dcu"
    - "*.tmp"

# Diretório do Projeto que a AI vai analisar
# Diretórios do Projeto
project_dir: "C://Users//User//Documents//GitHub//project"
backup_dir: "C://Users//User//Documents//GitHub//project-bkp"
log_dir: "C://Users//User//Documents//GitHub//project-bkp//logs"

# Modo Debug
debug: false